# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('redhat', 'Redhat\\CentOS/1-6/'), ('Centos7', 'CentOS7'), ('ubuntu', 'Ubuntu'), ('suse', 'Suse'), ('windows', 'Windows')], default='redhat', max_length=64),
        ),
    ]
